name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2.4.2
    - 
      name: Docker Login
      uses: docker/login-action@v2.0.0
      with: 
        username: yuntasha
        password: dckr_pat_W280xEphNaOuSaTC_4jxFD0aAP4
        
    - 
      name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        contect: .
        file: ./Dockerfile
        push: true
        tags: yuntasha/book-project
        labels: latest